import type { CodeEdit } from '../types';

export interface AIResponse {
  message: string;
  edits: CodeEdit[];
  agentId: string;
}

const editPatterns: Record<string, { filePath: string; transform: (content: string) => string; description: string }> = {
  'dark mode': {
    filePath: 'src/App.tsx',
    description: 'Added dark mode toggle with theme state',
    transform: (content) => {
      if (content.includes('darkMode')) return content;
      return content.replace(
        'export default function App() {',
        `export default function App() {
  const [darkMode, setDarkMode] = React.useState(true);`
      ).replace(
        "backgroundColor: '#030712'",
        "backgroundColor: darkMode ? '#030712' : '#F9FAFB'"
      ).replace(
        '<StatusBar style="light" />',
        `<Pressable onPress={() => setDarkMode(!darkMode)} style={styles.toggle}>
        <Text>{darkMode ? '🌙' : '☀️'}</Text>
      </Pressable>
      <StatusBar style={darkMode ? 'light' : 'dark'} />`
      );
    },
  },
  'button': {
    filePath: 'src/components/Button.tsx',
    description: 'Enhanced Button with glow effect and haptic feedback',
    transform: (content) =>
      content.replace(
        "backgroundColor: '#A855F7'",
        "backgroundColor: '#A855F7',\n    shadowColor: '#A855F7',\n    shadowOpacity: 0.4,\n    shadowRadius: 8"
      ),
  },
  'auth': {
    filePath: 'src/hooks/useAuth.ts',
    description: 'Fixed null reference bug in useAuth hook',
    transform: (content) =>
      content.replace(
        'setUser({ id: \'1\', email, name: \'Vibe Coder\' });',
        'setUser({ id: \'1\', email: email ?? \'\', name: \'Vibe Coder\' });'
      ),
  },
  'api': {
    filePath: 'src/services/api.ts',
    description: 'Added retry logic with exponential backoff',
    transform: (content) => {
      if (content.includes('retryWithBackoff')) return content;
      return `async function retryWithBackoff<T>(fn: () => Promise<T>, retries = 3): Promise<T> {
  for (let i = 0; i < retries; i++) {
    try { return await fn(); }
    catch (e) { if (i === retries - 1) throw e; await new Promise(r => setTimeout(r, 2 ** i * 500)); }
  }
  throw new Error('Max retries exceeded');
}

${content}`.replace(
        'const response = await fetch',
        'return retryWithBackoff(async () => {\n  const response = await fetch'
      ).replace(
        'return response.json();',
        'return response.json();\n});'
      );
    },
  },
  'terraform': {
    filePath: 'terraform/main.tf',
    description: 'Generated production-ready AWS infrastructure',
    transform: () => `# Generated by VibeCursor Cloud Factory
terraform {
  required_providers {
    aws = { source = "hashicorp/aws", version = "~> 5.0" }
  }
  backend "s3" {
    bucket = "vibecursor-terraform-state"
    key    = "prod/terraform.tfstate"
    region = "us-east-1"
  }
}

provider "aws" { region = var.aws_region }

variable "aws_region" { default = "us-east-1" }
variable "environment" { default = "production" }

resource "aws_lambda_function" "api" {
  function_name = "vibecursor-api-\${var.environment}"
  runtime       = "nodejs20.x"
  handler       = "index.handler"
  memory_size   = 512
  timeout       = 30
  reserved_concurrent_executions = 100
}

resource "aws_rds_cluster" "postgres" {
  cluster_identifier = "vibecursor-db-\${var.environment}"
  engine             = "aurora-postgresql"
  engine_mode        = "serverless"
  scaling_configuration {
    min_capacity = 2
    max_capacity = 16
  }
}

resource "aws_s3_bucket" "assets" {
  bucket = "vibecursor-assets-\${var.environment}"
}

resource "aws_cloudwatch_dashboard" "main" {
  dashboard_name = "vibecursor-\${var.environment}"
}
`,
  },
};

function detectIntent(prompt: string): string[] {
  const lower = prompt.toLowerCase();
  const intents: string[] = [];
  if (lower.includes('dark mode') || lower.includes('theme')) intents.push('dark mode');
  if (lower.includes('button') || lower.includes('glow')) intents.push('button');
  if (lower.includes('auth') || lower.includes('null') || lower.includes('bug')) intents.push('auth');
  if (lower.includes('api') || lower.includes('timeout') || lower.includes('retry')) intents.push('api');
  if (lower.includes('terraform') || lower.includes('cloud') || lower.includes('infrastructure') || lower.includes('aws') || lower.includes('gcp')) intents.push('terraform');
  return intents.length > 0 ? intents : ['button'];
}

function pickAgent(prompt: string): string {
  const lower = prompt.toLowerCase();
  if (lower.includes('terraform') || lower.includes('cloud') || lower.includes('deploy') || lower.includes('aws') || lower.includes('gcp')) return 'cloud-devops';
  if (lower.includes('bug') || lower.includes('fix') || lower.includes('error')) return 'qa';
  if (lower.includes('auth') || lower.includes('security') || lower.includes('secret')) return 'security';
  if (lower.includes('api') || lower.includes('database') || lower.includes('backend')) return 'backend';
  if (lower.includes('ui') || lower.includes('button') || lower.includes('theme') || lower.includes('style')) return 'frontend';
  return 'orchestrator';
}

export async function processAIRequest(
  prompt: string,
  files: { path: string; content: string }[]
): Promise<AIResponse> {
  await simulateThinking(1200 + Math.random() * 800);

  const intents = detectIntent(prompt);
  const agentId = pickAgent(prompt);
  const edits: CodeEdit[] = [];

  for (const intent of intents) {
    const pattern = editPatterns[intent];
    if (!pattern) continue;
    const file = files.find((f) => f.path === pattern.filePath);
    if (file) {
      edits.push({
        filePath: pattern.filePath,
        description: pattern.description,
        oldContent: file.content,
        newContent: pattern.transform(file.content),
      });
    }
  }

  const agentNames: Record<string, string> = {
    orchestrator: 'Orchestrator',
    frontend: 'Frontend Agent',
    backend: 'Backend Agent',
    'cloud-devops': 'Cloud DevOps Agent',
    qa: 'QA Agent',
    security: 'Security Agent',
  };

  const message =
    edits.length > 0
      ? `${agentNames[agentId]} applied ${edits.length} edit(s):\n\n${edits.map((e) => `• ${e.description} (${e.filePath})`).join('\n')}\n\nChanges are live in the Monaco editor. Review the diff and deploy when ready.`
      : `${agentNames[agentId]} analyzed your request. I understand you want to "${prompt}". Could you provide more specifics about which file or feature to modify?`;

  return { message, edits, agentId };
}

function simulateThinking(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

export async function diagnoseBug(
  bugTitle: string,
  stackTrace?: string,
  files?: { path: string; content: string }[]
): Promise<{ diagnosis: string; patch: CodeEdit | null }> {
  await simulateThinking(1000);

  const getFileContent = (path: string) => files?.find((f) => f.path === path)?.content ?? '';

  if (bugTitle.toLowerCase().includes('auth') || bugTitle.toLowerCase().includes('null')) {
    return {
      diagnosis:
        'Root cause: user object accessed before authentication completes. The hook returns null during the loading state but downstream code assumes a populated user.',
      patch: {
        filePath: 'src/hooks/useAuth.ts',
        description: 'Add null guard and loading state check',
        newContent: editPatterns.auth.transform(getFileContent('src/hooks/useAuth.ts')),
      },
    };
  }

  if (bugTitle.toLowerCase().includes('timeout') || bugTitle.toLowerCase().includes('api')) {
    return {
      diagnosis:
        'Root cause: fetch calls lack timeout configuration and retry logic. Under load, upstream services exceed the default 5s gateway timeout.',
      patch: {
        filePath: 'src/services/api.ts',
        description: 'Implement retry with exponential backoff',
        newContent: editPatterns.api.transform(getFileContent('src/services/api.ts')),
      },
    };
  }

  return {
    diagnosis: `Analyzed stack trace:\n${stackTrace ?? 'No trace available'}\n\nRecommend adding error boundaries and structured logging.`,
    patch: null,
  };
}
