import type { ProjectFile } from '../types';

export const sampleProjectFiles: ProjectFile[] = [
  {
    id: '1',
    path: 'src/App.tsx',
    name: 'App.tsx',
    language: 'typescript',
    content: `import React from 'react';
import { StatusBar } from 'expo-status-bar';
import { StyleSheet, Text, View } from 'react-native';

export default function App() {
  return (
    <View style={styles.container}>
      <Text style={styles.title}>Welcome to VibeCursor Pro</Text>
      <Text style={styles.subtitle}>Your AI coding companion</Text>
      <StatusBar style="light" />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#030712',
    alignItems: 'center',
    justifyContent: 'center',
  },
  title: {
    fontSize: 24,
    fontWeight: '700',
    color: '#A855F7',
  },
  subtitle: {
    fontSize: 16,
    color: '#9CA3AF',
    marginTop: 8,
  },
});
`,
  },
  {
    id: '2',
    path: 'src/components/Button.tsx',
    name: 'Button.tsx',
    language: 'typescript',
    content: `import React from 'react';
import { Pressable, Text, StyleSheet } from 'react-native';

interface ButtonProps {
  label: string;
  onPress: () => void;
  variant?: 'primary' | 'secondary';
}

export function Button({ label, onPress, variant = 'primary' }: ButtonProps) {
  return (
    <Pressable
      style={[styles.button, variant === 'secondary' && styles.secondary]}
      onPress={onPress}
    >
      <Text style={styles.label}>{label}</Text>
    </Pressable>
  );
}

const styles = StyleSheet.create({
  button: {
    backgroundColor: '#A855F7',
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 8,
  },
  secondary: {
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: '#3B82F6',
  },
  label: {
    color: '#FFFFFF',
    fontWeight: '600',
  },
});
`,
  },
  {
    id: '3',
    path: 'src/hooks/useAuth.ts',
    name: 'useAuth.ts',
    language: 'typescript',
    content: `import { useState, useCallback } from 'react';

interface User {
  id: string;
  email: string;
  name: string;
}

export function useAuth() {
  const [user, setUser] = useState<User | null>(null);
  const [loading, setLoading] = useState(false);

  const signIn = useCallback(async (email: string, password: string) => {
    setLoading(true);
    try {
      // TODO: Connect to Supabase auth
      await new Promise((r) => setTimeout(r, 800));
      setUser({ id: '1', email, name: 'Vibe Coder' });
    } finally {
      setLoading(false);
    }
  }, []);

  const signOut = useCallback(() => setUser(null), []);

  return { user, loading, signIn, signOut };
}
`,
  },
  {
    id: '4',
    path: 'src/services/api.ts',
    name: 'api.ts',
    language: 'typescript',
    content: `const API_BASE = process.env.EXPO_PUBLIC_API_URL ?? 'https://api.example.com';

export async function fetchData<T>(endpoint: string): Promise<T> {
  const response = await fetch(\`\${API_BASE}\${endpoint}\`);
  if (!response.ok) {
    throw new Error(\`API error: \${response.status}\`);
  }
  return response.json();
}

export async function postData<T>(endpoint: string, body: unknown): Promise<T> {
  const response = await fetch(\`\${API_BASE}\${endpoint}\`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(body),
  });
  if (!response.ok) {
    throw new Error(\`API error: \${response.status}\`);
  }
  return response.json();
}
`,
  },
  {
    id: '5',
    path: 'package.json',
    name: 'package.json',
    language: 'json',
    content: `{
  "name": "my-vibe-app",
  "version": "1.0.0",
  "main": "index.ts",
  "scripts": {
    "start": "expo start",
    "web": "expo start --web"
  },
  "dependencies": {
    "expo": "~57.0.0",
    "react": "19.0.0",
    "react-native": "0.79.0"
  }
}
`,
  },
  {
    id: '6',
    path: 'terraform/main.tf',
    name: 'main.tf',
    language: 'hcl',
    content: `# Generated by VibeCursor Cloud Factory
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = var.aws_region
}

variable "aws_region" {
  default = "us-east-1"
}
`,
  },
];

export const fileTree = [
  { name: 'src', type: 'folder' as const, children: [
    { name: 'App.tsx', type: 'file' as const, path: 'src/App.tsx' },
    { name: 'components', type: 'folder' as const, children: [
      { name: 'Button.tsx', type: 'file' as const, path: 'src/components/Button.tsx' },
    ]},
    { name: 'hooks', type: 'folder' as const, children: [
      { name: 'useAuth.ts', type: 'file' as const, path: 'src/hooks/useAuth.ts' },
    ]},
    { name: 'services', type: 'folder' as const, children: [
      { name: 'api.ts', type: 'file' as const, path: 'src/services/api.ts' },
    ]},
  ]},
  { name: 'terraform', type: 'folder' as const, children: [
    { name: 'main.tf', type: 'file' as const, path: 'terraform/main.tf' },
  ]},
  { name: 'package.json', type: 'file' as const, path: 'package.json' },
];
